name: "Terraform Run"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-run:
    name: "Terraform Run"
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./example
    env:
      TF_CLOUD_ORGANIZATION: myorg
      TF_CLOUD_HOSTNAME: tfe.simon-lynch.sbx.hashidemos.io
      TF_CLOUD_PROJECT: platform_team
      TF_WORKSPACE: example_workspace
      TF_TOKEN_tfe_simon-lynch_sbx_hashidemos_io: ${{ secrets.TFE_TOKEN }}
      TFE_TOKEN:
    steps:
      - name: Update CA certificates
        run: |
          echo "${{ secrets.ROOT_CA_CERT }}" | sudo tee /usr/local/share/ca-certificates/root_ca.crt > /dev/null
          sudo update-ca-certificates
      - name: Checkout
        uses: actions/checkout@v4.1.7
      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          cli_config_credentials_hostname: 'tfe.simon-lynch.sbx.hashidemos.io'
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
      # Run Terraform Init
      - name: Terraform Init, create TFC workspace
        id: tf-init
      #  if: github.event_name == 'pull_request'
        run: |
          terraform init
      # Run Terraform Apply
      - name: Terraform Apply
      #  if: github.event_name == 'pull_request' && github.event.action != 'closed'
        id: tf-apply
        run: |
          terraform apply --auto-approve
      # Runs Terraform output
      - name: Terraform Output
        id: output
      #  if: github.event_name == 'pull_request' && github.event.action != 'closed'
        run: |
          terraform output
        continue-on-error: true
      # Creates comments on pull request with Terraform output